(add-to-list 'load-path prelude-personal-dir)

;; disable default theme (zenburn)
(disable-theme 'zenburn)

(require 'htmlize-goldbar)
(require 'powerline-goldbar)
(require 'theme-goldbar)
(require 'helm-goldbar)
(require 'company-goldbar)
(require 'latex-goldbar)
(require 'e2wm-goldbar)
(require 'eclim-goldbar)
(require 'java-goldbar)
(require 'scala-goldbar)
(require 'misc-goldbar)
